# Generated by Django 4.1.3 on 2022-11-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Факультеты'},
        ),
    ]
