# Generated by Django 4.1.3 on 2022-11-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Группы'},
        ),
    ]
