# Generated by Django 4.1.3 on 2022-11-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Форма обучения',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='education_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.educationform'),
        ),
    ]
