# Generated by Django 4.1.3 on 2022-11-03 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 5, 26, 30, 502222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 5, 26, 30, 501568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 5, 26, 30, 501918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studyplandisciplines',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 5, 26, 30, 502468, tzinfo=datetime.timezone.utc)),
        ),
    ]
